server:
  port: 8081
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3307/user_service_db

user:
  service:
    name: "User Service"
    version: "1.0"
    description: "micro service for managing user info"
